#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
# test_contract.py: The data contract with finance-dashboard
#
#  Description:
#  Pin the format of every file this repository generates, in the terms
#  the consumer reads them in.
#
#  finance-dashboard holds no copy of this repository's code. The two
#  are joined by a directory of files, and the joint is only as good as
#  these assertions. Two properties of the consumer make that sharper
#  than it sounds:
#
#  - Summary files are parsed positionally. finance_dashboard/data.py
#    skips the header line, splits on tab and zips the fields against a
#    fixed list of names. A column inserted, removed or reordered here
#    does not fail there; it silently shifts every later value into the
#    wrong name. The parser below is written the same way on purpose.
#  - ti_CODE.csv is parsed by header name through csv.DictReader, with
#    each name lowercased and non-alphanumerics collapsed to
#    underscores. Renaming a column breaks it; reordering does not.
#
#  The indicator file is checked against test/ti_N225.csv, which was
#  generated by the implementation this one replaces. Regenerating its
#  computed indicator columns and finding them equal is what shows the
#  contract survived the rewrite.
#
#  Test Cases:
#  - Regenerated indicator columns match the committed fixture.
#  - ti_CODE.csv keeps its name, separator, index label, column order
#    and header spelling, and normalizes to the keys the dashboard reads.
#  - classified and predicted appear on the last row only.
#  - stock_CODE.csv keeps its six columns in canonical order.
#  - The ten and nine column summary layouts parse positionally into the
#    dashboard's own column lists.
#  - stocks.txt parses as code and name.
#  - data_source.txt states the source and the last trading day, and an
#    unknown last trading day is left empty rather than filled with
#    today.
#  - History files carry the dated double extension.
#  - Chart file names follow the window length rule.
#
#  Author: id774 (More info: http://id774.net)
#  Source Code: https://github.com/id774/finance
#  License: The GPL version 3, or LGPL version 3 (Dual License).
#  Contact: idnanashi@gmail.com
#
#  Requirements:
#  - Python Version: 3.11 or later
#  - pandas, pytest
#
#  Version History:
#  v1.0 2026-08-14
#       Pin data_source.txt, which tells the dashboard how old the data
#       it is showing is.
#       Initial release.
#  v1.1 2026-08-24
#       Keep provenance text independent from data age and verify the
#       generation and trading dates as separate facts.
#
########################################################################

from __future__ import annotations

import csv
import re
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from finance import storage
from finance.aggregation import Aggregator
from finance.charts import chart_filename, chart_prefix
from finance.datasources import CANONICAL_COLUMNS
from finance.indicators import build_indicator_frame
from finance.stocklist import read_stock_list

# Copied from finance_dashboard/data.py. They are duplicated here rather
# than imported because finance must not depend on the dashboard at
# runtime or in its tests; that these two lists agree with the ones over
# there is the contract, and a copy is what lets a mismatch be seen.
DASHBOARD_PORTFOLIO_COLUMNS = (
    "code",
    "open",
    "high",
    "low",
    "close",
    "diff",
    "ratio",
    "trend",
    "predict",
    "name",
)

DASHBOARD_SUMMARY_COLUMNS = (
    "code",
    "open",
    "high",
    "low",
    "close",
    "diff",
    "ratio",
    "rsi",
    "name",
)

# The indicator column names finance_dashboard/indicators.py looks up,
# after its header normalization.
DASHBOARD_INDICATOR_KEYS = (
    "date",
    "open",
    "high",
    "low",
    "adj_close",
    "volume",
    "ewma5",
    "ewma25",
    "ewma50",
    "ewma75",
    "ewma200",
    "upperband",
    "lowerband",
    "sar",
    "ret_index",
    "rsi9",
    "rsi14",
    "mfi14",
    "roc10",
    "roc25",
    "roc50",
    "roc75",
    "roc150",
    "cci14",
    "ultosc",
    "slowk",
    "slowd",
    "fastk",
    "fastd",
    "macd",
    "macdsignal",
    "macdhist",
    "willr14",
    "vl",
    "tr",
    "atr",
    "natr",
)

PRICE_COLUMNS = ("Open", "High", "Low", "Close", "Volume", "Adj Close")


def normalize_header(name: str) -> str:
    """ Normalize a header cell exactly as finance_dashboard/data.py does. """
    return re.sub(r"[^0-9a-z]+", "_", (name or "").strip().lower()).strip("_")


def read_summary_as_dashboard(path, columns) -> list[dict[str, str]]:
    """ Parse a summary file the way finance_dashboard/data.py parses it. """
    rows: list[dict[str, str]] = []
    with open(path, encoding="utf-8", errors="replace") as handle:
        for line in handle:
            fields = line.rstrip("\n").split("\t")
            if not fields or not fields[0] or fields[0] == "Code":
                continue
            row = dict(zip(columns, fields, strict=False))
            for column in columns:
                row.setdefault(column, "")
            rows.append(row)
    return rows


def read_indicators_as_dashboard(path) -> list[dict[str, str]]:
    """ Parse an indicator file the way finance_dashboard/data.py parses it. """
    rows: list[dict[str, str]] = []
    with open(path, encoding="utf-8", errors="replace", newline="") as handle:
        for record in csv.DictReader(handle):
            row = {
                normalize_header(key): (value or "")
                for key, value in record.items()
                if key
            }
            if not row.get("date") or row.get("date") == "Date":
                continue
            rows.append(row)
    return rows


# --------------------------------------------------------------------
# ti_CODE.csv
# --------------------------------------------------------------------


def test_regenerated_indicators_match_the_committed_fixture(raw_prices, indicator_fixture):
    """ Every computed column of ti_N225.csv reproduces from stock_N225.csv. """
    computed = build_indicator_frame(raw_prices).stock

    checked = 0
    for column in indicator_fixture.columns:
        if column in PRICE_COLUMNS or column in ("classified", "predicted"):
            continue
        assert column in computed.columns, "lost column {0}".format(column)

        expected = indicator_fixture[column].astype("float64")
        actual = computed[column].reindex(indicator_fixture.index).astype("float64")

        # The pattern of leading NaNs is part of the contract: it is how
        # long each indicator takes to warm up, and the dashboard renders
        # those cells empty.
        assert (expected.isna() == actual.isna()).all(), "NaN pattern moved in {0}".format(column)

        both = expected.notna()
        np.testing.assert_allclose(
            actual[both].to_numpy(),
            expected[both].to_numpy(),
            rtol=1e-12,
            atol=0,
            err_msg="values moved in {0}".format(column),
        )
        checked += 1

    assert checked == 42, "expected 42 computed columns, checked {0}".format(checked)


def test_indicator_file_keeps_its_format(settings, raw_prices):
    indicators = build_indicator_frame(raw_prices).stock
    merged = storage.merge_frames(raw_prices, indicators)
    path = settings.data_file(storage.indicator_filename("N225"))
    storage.write_price_csv(merged, path)

    assert path.name == "ti_N225.csv"
    header = path.read_text(encoding="utf-8").splitlines()[0]
    assert header.startswith("Date,")
    assert "\t" not in header

    columns = header.split(",")
    assert columns[:7] == ["Date", "Open", "High", "Low", "Close", "Volume", "Adj Close"]


def test_indicator_file_matches_the_fixture_header(settings, raw_prices, indicator_fixture):
    """ The generated header is spelled exactly as the committed one. """
    indicators = build_indicator_frame(raw_prices).stock
    indicators.loc[indicators.index[-1], "classified"] = 0
    indicators.loc[indicators.index[-1], "predicted"] = 19125
    merged = storage.merge_frames(raw_prices, indicators)
    path = settings.data_file(storage.indicator_filename("N225"))
    storage.write_price_csv(merged, path)

    generated = path.read_text(encoding="utf-8").splitlines()[0].split(",")
    expected = ["Date"] + list(indicator_fixture.columns)
    assert generated == expected


def test_indicator_file_normalizes_to_the_keys_the_dashboard_reads(settings, raw_prices):
    indicators = build_indicator_frame(raw_prices).stock
    merged = storage.merge_frames(raw_prices, indicators)
    path = settings.data_file(storage.indicator_filename("N225"))
    storage.write_price_csv(merged, path)

    rows = read_indicators_as_dashboard(path)
    assert rows, "the dashboard parser found no rows"
    for key in DASHBOARD_INDICATOR_KEYS:
        assert key in rows[0], "the dashboard would not find {0}".format(key)


def test_model_outputs_appear_on_the_last_row_only(settings, raw_prices):
    indicators = build_indicator_frame(raw_prices).stock
    indicators.loc[indicators.index[-1], "classified"] = 1
    indicators.loc[indicators.index[-1], "predicted"] = 20000
    merged = storage.merge_frames(raw_prices, indicators)
    path = settings.data_file(storage.indicator_filename("N225"))
    storage.write_price_csv(merged, path)

    written = pd.read_csv(path, index_col=0, parse_dates=True)
    assert written["classified"].notna().sum() == 1
    assert written["predicted"].notna().sum() == 1
    assert bool(written["classified"].notna().iloc[-1])
    assert bool(written["predicted"].notna().iloc[-1])


# --------------------------------------------------------------------
# stock_CODE.csv
# --------------------------------------------------------------------


def test_price_file_keeps_its_name_and_columns(settings, raw_prices):
    path = settings.data_file(storage.price_filename("N225"))
    storage.write_price_csv(raw_prices, path)

    assert path.name == "stock_N225.csv"
    header = path.read_text(encoding="utf-8").splitlines()[0]
    assert header == "Date," + ",".join(PRICE_COLUMNS)


def test_canonical_column_order_is_the_stored_order():
    """ The data source's canonical order is the order on disk. """
    assert CANONICAL_COLUMNS == PRICE_COLUMNS


def test_committed_fixture_uses_the_canonical_order():
    header = (
        (Path(__file__).parent / "stock_N225.csv").read_text(encoding="utf-8").splitlines()[0]
    )
    assert header == "Date," + ",".join(PRICE_COLUMNS)


# --------------------------------------------------------------------
# Summary files
# --------------------------------------------------------------------


def build_frames(indicator_fixture: pd.DataFrame, today: date) -> dict:
    """ Build two indicator frames dated so that they count as current. """
    frame = indicator_fixture.copy()
    frame.loc[frame.index[-1], "classified"] = 1
    frame.loc[frame.index[-1], "predicted"] = 19125
    shifted = frame.copy()
    shifted.index = pd.date_range(end=pd.Timestamp(today), periods=len(frame), freq="B")
    other = shifted.copy()
    other["Adj Close"] = other["Adj Close"] * 0.5
    return {("7203", "トヨタ"): shifted, ("6758", "ソニー"): other}


def test_portfolio_layout_parses_positionally(settings, indicator_fixture, today):
    frames = build_frames(indicator_fixture, today)
    table = Aggregator(frames).summarize(span=1, sortkey="Ratio", as_of=today)
    path = settings.data_file("portfolio.csv")
    storage.write_summary_csv(table, path)

    header = path.read_text(encoding="utf-8").splitlines()[0]
    assert header.split("\t") == [
        "Code",
        "Open",
        "High",
        "Low",
        "Close",
        "Change",
        "Ratio",
        "Trend",
        "Pred",
        "Name",
    ]

    rows = read_summary_as_dashboard(path, DASHBOARD_PORTFOLIO_COLUMNS)
    assert len(rows) == 2
    for row in rows:
        assert row["code"] in {"7203", "6758"}
        assert row["name"] in {"トヨタ", "ソニー"}
        # A shifted column would put a name where a number belongs.
        for numeric in ("open", "high", "low", "close", "diff", "ratio", "predict"):
            float(row[numeric])
        assert row["trend"] in {"0", "1"}


def test_screening_layout_parses_positionally(settings, indicator_fixture, today):
    frames = build_frames(indicator_fixture, today)
    table = Aggregator(frames).summarize(
        span=1, sortkey="rsi14", ascending=True, screening_key="rsi14", as_of=today
    )
    path = settings.data_file("screening_rsi14.csv")
    storage.write_summary_csv(table, path)

    header = path.read_text(encoding="utf-8").splitlines()[0]
    assert header.split("\t") == [
        "Code",
        "Open",
        "High",
        "Low",
        "Close",
        "Change",
        "Ratio",
        "rsi14",
        "Name",
    ]

    rows = read_summary_as_dashboard(path, DASHBOARD_SUMMARY_COLUMNS)
    assert len(rows) == 2
    for row in rows:
        for numeric in ("open", "high", "low", "close", "diff", "ratio", "rsi"):
            float(row[numeric])
        assert row["name"] in {"トヨタ", "ソニー"}


def test_core30_layout_uses_the_nine_column_form(settings, indicator_fixture, today):
    frames = build_frames(indicator_fixture, today)
    table = Aggregator(frames).summarize(
        span=1, sortkey="Ratio", screening_key="rsi9", as_of=today
    )
    path = settings.data_file("topix_core30.csv")
    storage.write_summary_csv(table, path)

    rows = read_summary_as_dashboard(path, DASHBOARD_SUMMARY_COLUMNS)
    assert len(rows) == 2
    for row in rows:
        # The dashboard labels this column RSI9 and reads it as "rsi".
        float(row["rsi"])


def test_summary_values_are_truncated_integers(settings, indicator_fixture, today):
    frames = build_frames(indicator_fixture, today)
    table = Aggregator(frames).summarize(span=1, as_of=today)
    path = settings.data_file("summary.csv")
    storage.write_summary_csv(table, path)

    rows = read_summary_as_dashboard(path, DASHBOARD_PORTFOLIO_COLUMNS)
    for row in rows:
        for column in ("open", "high", "low", "close", "diff", "predict"):
            assert "." not in row[column], "{0} should be an integer".format(column)


def test_summary_separator_is_a_tab(settings, indicator_fixture, today):
    frames = build_frames(indicator_fixture, today)
    table = Aggregator(frames).summarize(span=1, as_of=today)
    path = settings.data_file("summary.csv")
    storage.write_summary_csv(table, path)

    text = path.read_text(encoding="utf-8")
    assert "\t" in text
    # A comma inside a Japanese company name would still be quoted, but
    # no field separator may be a comma.
    assert text.splitlines()[0].count(",") == 0


# --------------------------------------------------------------------
# stocks.txt, history, chart names
# --------------------------------------------------------------------


def test_stocks_txt_parses_as_code_and_name(settings):
    path = settings.data_file("stocks.txt")
    path.write_text("6758,ソニー\n7203,トヨタ,トヨタ自動車(株)\n", encoding="utf-8")
    entries = read_stock_list(path)

    assert [(e.code, e.name) for e in entries] == [
        ("6758", "ソニー"),
        ("7203", "トヨタ"),
    ]
    # The dashboard splits the same line on a comma and takes two fields.
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.strip().split(",")
        assert len(fields) >= 2 and fields[0]


# --------------------------------------------------------------------
# data_source.txt
# --------------------------------------------------------------------

# Copied from finance_dashboard/data.py, for the same reason as the
# summary columns above: the duplication is the contract.
DASHBOARD_DATA_SOURCE_FILE = "data_source.txt"
DASHBOARD_DATA_SOURCE_KEYS = ("source", "generated", "last_trading_day")


def read_as_the_dashboard_does(path) -> dict:
    """ Parse data_source.txt the way finance_dashboard/data.py does. """
    values = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        key, _, value = line.partition("\t")
        values[key.strip()] = value.strip()
    return values


def test_data_source_states_the_source_and_the_last_trading_day(settings, today):
    path = settings.data_file(DASHBOARD_DATA_SOURCE_FILE)
    storage.write_data_source(path, "J-Quants API (Free plan)", today, date(2015, 3, 20))

    values = read_as_the_dashboard_does(path)
    assert list(values) == list(DASHBOARD_DATA_SOURCE_KEYS)
    assert values["source"] == "J-Quants API (Free plan)"
    assert values["generated"] == "2015-03-23"
    assert values["last_trading_day"] == "2015-03-20"


def test_generation_and_trading_dates_are_kept_separate(settings, today):
    """
    Keep the generation date and the last trading day as separate facts.

    The two values may differ, and recording both lets the dashboard show
    the age of the data without inferring it from the day the job ran.
    """
    path = settings.data_file(DASHBOARD_DATA_SOURCE_FILE)
    storage.write_data_source(path, "source", today, date(2015, 3, 20))

    values = read_as_the_dashboard_does(path)
    assert values["last_trading_day"] < values["generated"]


def test_an_unknown_last_trading_day_is_empty_rather_than_today(settings, today):
    path = settings.data_file(DASHBOARD_DATA_SOURCE_FILE)
    storage.write_data_source(path, "source", today, None)

    values = read_as_the_dashboard_does(path)
    assert values["last_trading_day"] == ""
    assert values["generated"] == "2015-03-23"


def test_the_file_name_and_separator_are_what_the_dashboard_expects():
    assert storage.DATA_SOURCE_FILE == DASHBOARD_DATA_SOURCE_FILE
    assert storage.DATA_SOURCE_KEYS == DASHBOARD_DATA_SOURCE_KEYS


def test_history_file_name_carries_the_date(settings, indicator_fixture, today):
    name = storage.history_filename("summary.csv", today)
    assert name == "summary.csv.20150323.csv"

    frames = build_frames(indicator_fixture, today)
    table = Aggregator(frames).summarize(span=1, as_of=today)
    path = settings.history_file(name)
    storage.write_summary_csv(table, path)
    assert path.is_file()
    assert path.parent.name == "history"


@pytest.mark.parametrize(
    ("days", "expected"),
    [(600, "long"), (301, "long"), (300, "chart"), (240, "chart"), (61, "chart"),
     (60, "short"), (30, "short")],
)
def test_chart_prefix_follows_the_window(days, expected):
    assert chart_prefix(days) == expected


def test_chart_file_names_match_what_the_dashboard_requests():
    assert chart_filename("chart", "N225") == "chart_N225.png"
    assert chart_filename("long", "N225") == "long_N225.png"
    assert chart_filename("short", "7203") == "short_7203.png"
